### ISSUE TITLE
Github link for ROS noetic moveit toutorial not working

### ISSUE THREAD

**Issue by AbrarMahmud** [moveit/moveit_tutorials#819]
### Description

Github link for ROS noetic moveit toutorial not working

### Your environment
* ROS Distro: noetic
* OS Version: e.g. Ubuntu 20.04 

### Steps to reproduce
![Screenshot_20240430_120534](https://github.com/moveit/moveit_tutorials/assets/62346485/1fb8acd3-bf8e-4f1a-91cf-b7e0ad215275)

If i try to open this link :
https://ros-planning.github.io/moveit_tutorials/

It seems to be removed !
![Screenshot_20240430_115445](https://github.com/moveit/moveit_tutorials/assets/62346485/201fd2a6-751e-43c9-8107-74a657f74287)

**Comment by rhaschke** [comment]
I opened https://github.com/moveit/moveit.ros.org/pull/847 to update the hyperlinks.
