### ISSUE TITLE
github404

### ISSUE THREAD

**Issue by ShanningZhuang** [moveit/moveit_tutorials#821]
The document of moveit 1 is 404.
[ros-planning.github.io/moveit_tutorials/](https://ros-planning.github.io/moveit_tutorials/)

**Comment by rhaschke** [comment]
The tutorials were migrated to https://moveit.github.io/moveit_tutorials. Where did you find the broken link?

**Comment by ShanningZhuang** [comment]
> The tutorials were migrated to https://moveit.github.io/moveit_tutorials. Where did you find the broken link?

Thanks! The link you gave me is correct. I found the broken link in this repository's about and in google.

**Comment by torydebra** [comment]
The old link is also present on the moveit2 page https://moveit.picknik.ai/main/index.html, at the top there is `see [MoveIt 1 tutorials](https://ros-planning.github.io/moveit_tutorials).`
