### ISSUE TITLE
The noetic branch of moveit_tutorials is missing.

### ISSUE THREAD

**Issue by zhihao10096** [moveit/moveit_tutorials#822]
Hello. The noetic branch of moveit_tutorials is missing.

**Comment by rhaschke** [comment]
It's simply called `master`.

**Comment by zhihao10096** [comment]
Ok thanks. But this page doesn't open correctly :https://ros-planning.github.io/moveit_tutorials/doc/perception_pipeline/perception_pipeline_tutorial.html

**Comment by zhihao10096** [comment]
Noetic's tutorials are no longer available.
https://ros-planning.github.io/moveit_tutorials/

**Comment by rhaschke** [comment]
The tutorials have been migrated to https://moveit.github.io/moveit_tutorials

**Comment by zhihao10096** [comment]
OK. Thanks.
