### ISSUE TITLE
File panda_gripper_moveit_controller_manager.launch.xml does not exist

### ISSUE THREAD

**Issue by illusionsoftruth** [moveit/moveit_tutorials#829]
Environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04

I am trying to run panda simulator with moveit for the link below:-

[https://github.com/justagist/panda_simulator](https://github.com/moveit/panda_moveit_config/url)

The simulator starts running and opens Gazebo with the arm
`roslaunch panda_gazebo panda_world.launch`

<img width="1470" alt="Screenshot 2024-09-19 at 6 10 23 PM" src="https://github.com/user-attachments/assets/d020c7eb-001c-40ab-9351-b3ddc148c4e7">

After running the above code, I try to run `roslaunch panda_sim_moveit sim_move_group.launch`  in another terminal and I get this error:-

**illusionsoftruth@luciddreamingguy:**~/catkin_ws$ roslaunch panda_sim_moveit sim_move_group.launch
... logging to /home/illusionsoftruth/.ros/log/25659982-76a1-11ef-a8f1-53b05bbf11d5/roslaunch-luciddreamingguy-530622.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

**RLException: while processing /home/illusionsoftruth/catkin_ws/src/panda_moveit_config/launch/trajectory_execution.launch.xml:
while processing /home/illusionsoftruth/catkin_ws/src/panda_moveit_config/launch/panda_gripper_moveit_controller_manager.launch.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/home/illusionsoftruth/catkin_ws/src/panda_moveit_config/launch/panda_gripper_moveit_controller_manager.launch.xml'
The traceback for the exception was written to the log file**

It is trying to search for the file **panda_gripper_moveit_controller_manager.launch.xml** but that file doesnt exist in that location.

**illusionsoftruth@luciddreamingguy:**~/catkin_ws/src/panda_moveit_config/launch$ ls
chomp_planning_pipeline.launch.xml
default_warehouse_db.launch
demo_chomp.launch
demo_gazebo.launch
demo.launch
demo_lerp.launch
demo_stomp.launch
fake_moveit_controller_manager.launch.xml
franka_control.launch
joystick_control.launch
lerp_planning_pipeline.launch.xml
move_group.launch
moveit_empty.rviz
moveit.rviz
moveit_rviz.launch
moveit_scene.rviz
ompl-chomp_planning_pipeline.launch.xml
ompl_planning_pipeline.launch.xml
panda_moveit_sensor_manager.launch.xml
pilz_industrial_motion_planner_planning_pipeline.launch.xml
planning_context.launch
planning_pipeline.launch.xml
ros_controllers.launch
ros_control_moveit_controller_manager.launch.xml
run_benchmark_ompl.launch
run_benchmark_trajopt.launch
sensor_manager.launch.xml
setup_assistant.launch
simple_moveit_controller_manager.launch.xml
stomp_planning_pipeline.launch.xml
trajectory_execution.launch.xml
trajopt_planning_pipeline.launch.xml
warehouse.launch
warehouse_settings.launch.xml

Can someone help me with this?

**Comment by rhaschke** [comment]
This seems to be a cross-post of https://github.com/moveit/panda_moveit_config/issues/144.
