### ISSUE TITLE
catkin build errors with moveit1 for noetic

### ISSUE THREAD

**Issue by addy1997** [moveit/moveit_tutorials#830]
### Description

Error related to computeCartesianPath function

error: no matching function for call to ‘moveit::planning_interface::MoveGroupInterface::computeCartesianPath(std::vector<geometry_msgs::Pose_<std::allocator<void> > >&, const double&, moveit_msgs::RobotTrajectory&)’

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Source
* If source, which git commit or tag - [6ce67d1](https://github.com/moveit/moveit_tutorials/commit/6ce67d1cb4f9792f064253481d7d0455a882f61c)

### Steps to reproduce
This issue can be reproduced by following the build instructions from the official moveit page

### Expected behaviour
Expecting it to install normally.

### Backtrace or Console output
![image](https://github.com/user-attachments/assets/b9815d8c-9211-4571-8f5e-b5d661e526e6)

All other packages install properly except moveit_tutorial. Please could you suggest something?

**Comment by rhaschke** [comment]
The latest commit of moveit_tutorials (6ce67d1) requires the latest source of MoveIt as well. If you are using the binary release (version 1.1.14), you should use commit b694b64e2dc980ecd88885efb357248faadeacb0 instead.

**Comment by addy1997** [comment]
> The latest commit of moveit_tutorials ([6ce67d1](https://github.com/moveit/moveit_tutorials/commit/6ce67d1cb4f9792f064253481d7d0455a882f61c)) requires the latest source of MoveIt as well. If you are using the binary release (version 1.1.14), you should use commit [b694b64](https://github.com/moveit/moveit_tutorials/commit/b694b64e2dc980ecd88885efb357248faadeacb0) instead.

@rhaschke, thanks I fixed it.
